# This file contains values from Cookiecutter

default_context:
  project_name: "python-fixturify-project"
  project_description: "Dynamic fixture creation for your tests"
  organization: "scalvert"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "python-fixturify-project"
  email: "steve.calvert@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
